---
  driver:
    name: vagrant

  provisioner:
    name: ansible_playbook
    require_chef_for_busser: false
    require_ruby_for_busser: true
    ansible_verbosity: 2
    ansible_verbose: true
    ansible_yum_repo: "https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"
    hosts: all

  platforms:
    - name: ubuntu-14.04
      driver_config:
        box: bento/ubuntu-14.04
    - name: centos-7.1
      driver_config:
         box: bento/centos-7.1

  verifier:
    ruby_bindir: '/usr/bin'

  suites:
    - name: default